apiVersion: v1
kind: Service
metadata:
  name: nodejs-test-service  # Nombre del servicio
spec:
  selector:
    app: nodejs-test-app  # Selecciona los pods que tienen esta etiqueta
  ports:
    - protocol: TCP
      port: 80  # Puerto que expone el servicio externamente
      targetPort: 3000  # Puerto en el que escucha la aplicación dentro del pod
  type: LoadBalancer  # Tipo de servicio para balancear la carga
