name: CI/CD for NestJS App

on:
  push:
    branches:
      - master  # Cambia por la rama que desees desplegar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Cambia por la versión de Node.js que uses

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Paso 4: Compilar la aplicación
      - name: Build the app
        run: npm run build

      # Paso 5: Construir la imagen Docker
      - name: Build Docker image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: docker build -t "${DOCKER_USER}"/devops-app:latest .

      # Paso 6: Autenticarse en Docker Hub usando DOCKER_USER y DOCKER_TOKEN
      - name: Log in to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USER}" --password-stdin

      # Paso 7: Push de la imagen a Docker Hub
      - name: Push Docker image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: docker push "${DOCKER_USER}"/devops-app:latest

      # Paso 8: Desplegar en EC2
      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}  # IP pública o DNS de tu EC2
          EC2_USER: ${{ secrets.EC2_USER }}  # Usuario para SSH (ec2-user)
          EC2_KEY: ${{ secrets.EC2_KEY }}    # Clave privada SSH, almacenada en Secrets de GitHub
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 400 key.pem
          ssh -i key.pem $EC2_USER@$EC2_HOST "docker pull $DOCKER_USER/devops-app:latest && docker stop nestjs-container || true && docker rm nestjs-container || true && docker run -d --name nestjs-container -p 3000:3000 $DOCKER_USER/devops-app:latest"

      # Paso 9: Limpiar archivos temporales
      - name: Clean up
        run: rm -f key.pem
