name: CI/CD for NestJS App

on:
  push:
    branches:
      - main  # Cambia por la rama que desees desplegar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Cambia por la versión de Node.js que uses

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Paso 4: Build de la aplicación
      - name: Build the app
        run: npm run build

      # Paso 5: Subir archivos al servidor EC2
      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}  # IP pública o DNS de tu EC2
          EC2_USER: ${{ secrets.EC2_USER }}  # Usuario para SSH (ec2-user)
          EC2_KEY: ${{ secrets.EC2_KEY }}    # Clave privada SSH, almacenada en Secrets de GitHub
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 400 key.pem
          scp -i key.pem -r ./app/* $EC2_USER@$EC2_HOST:/ruta/destino/en/ec2
          ssh -i key.pem $EC2_USER@$EC2_HOST "cd /ruta/destino/en/ec2 && npm install --production && pm2 restart app"

      # Paso 6: Limpiar archivos temporales
      - name: Clean up
        run: rm -f key.pem
